#!/usr/bin/env bash
################################################################################
# @ddblock_begin copyright
#
# Copyright (c) 1997-2018
# Maryland DSPCAD Research Group, The University of Maryland at College Park 
#
# Permission is hereby granted, without written agreement and without
# license or royalty fees, to use, copy, modify, and distribute this
# software and its documentation for any purpose, provided that the above
# copyright notice and the following two paragraphs appear in all copies
# of this software.
# 
# IN NO EVENT SHALL THE UNIVERSITY OF MARYLAND BE LIABLE TO ANY PARTY
# FOR DIRECT, INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES
# ARISING OUT OF THE USE OF THIS SOFTWARE AND ITS DOCUMENTATION, EVEN IF
# THE UNIVERSITY OF MARYLAND HAS BEEN ADVISED OF THE POSSIBILITY OF
# SUCH DAMAGE.
# 
# THE UNIVERSITY OF MARYLAND SPECIFICALLY DISCLAIMS ANY WARRANTIES,
# INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE. THE SOFTWARE
# PROVIDED HEREUNDER IS ON AN "AS IS" BASIS, AND THE UNIVERSITY OF
# MARYLAND HAS NO OBLIGATION TO PROVIDE MAINTENANCE, SUPPORT, UPDATES,
# ENHANCEMENTS, OR MODIFICATIONS.
#
# @ddblock_end copyright
################################################################################

# Script to configure this project

dloclincludepath="-I. -I$UXLIDEOCL/src/gems/actors/basic \
-I$UXLIDEOCL/src/gems/graph/common -I$UXLIDEOCL/src/gems/graph/basic \
-I$UXLIDEOCL/src/gems/edges/basic -I$UXLIDEOCL/src/gems/actors/common \
-I$UXLIDEOCL/src/tools/runtime"
dloclmiscflags=""
dloclmiscldflags=""
dlocllibpath=""
dlocllibs="$LIDEOCLGEN/lide_ocl_graph_basic.a \
$LIDEOCLGEN/lide_ocl_actors_basic.a \
$LIDEOCLGEN/lide_ocl_edges_basic.a $LIDEOCLGEN/lide_ocl_runtime.a"
dlocltargetfile="lide_ocl_inner_product_driver.exe"
dloclinstalldir="$LIDEOCLGEN"
dloclobjs="lide_ocl_inner_product_driver.o"
dloclverbose=""
dloclcompiler="g++"
